namespace Walk.TextEditor.RazorLib.Decorations.Models;

public class GenericDecorationMapper : IDecorationMapper
{
    public string Map(byte decorationByte)
    {
        var decoration = (GenericDecorationKind)decorationByte;

        return decoration switch
        {
            GenericDecorationKind.None => string.Empty,
            GenericDecorationKind.Keyword => "di0",
            GenericDecorationKind.KeywordControl => "di4",
            GenericDecorationKind.EscapeCharacterPrimary => "di7",
            GenericDecorationKind.EscapeCharacterSecondary => "di7 di8",
            GenericDecorationKind.StringLiteral => "di6",
            GenericDecorationKind.Variable => "di1",
            GenericDecorationKind.CommentSingleLine => "di5",
            GenericDecorationKind.CommentMultiLine => "di5",
            GenericDecorationKind.Function => "di3",
            GenericDecorationKind.PreprocessorDirective => "di9",
            GenericDecorationKind.DeliminationExtended => "di6",
            GenericDecorationKind.Type => "di2",
            ///
            GenericDecorationKind.Css_Identifier => "di_css-identifier",
            GenericDecorationKind.Css_PropertyName => "di_css-property-name",
            GenericDecorationKind.Css_PropertyValue => "di_css-property-value",
            GenericDecorationKind.Css_Comment => "di_comment",
            GenericDecorationKind.Css_Function => "di_method",
            ///
            GenericDecorationKind.Json_PropertyKey => "di_json-property-key",
            GenericDecorationKind.Json_String => "di_string",
            GenericDecorationKind.Json_Number => "di_te_number",
            GenericDecorationKind.Json_Integer => "di_te_integer",
            GenericDecorationKind.Json_Keyword => "di_keyword",
            GenericDecorationKind.Json_LineComment => "di_comment",
            GenericDecorationKind.Json_BlockComment => "di_comment",
            GenericDecorationKind.Json_Null => string.Empty,
            GenericDecorationKind.Json_Document => string.Empty,
            GenericDecorationKind.Json_Error => string.Empty,
            ///
            GenericDecorationKind.Xml_AttributeName => "di_attribute-name",
            GenericDecorationKind.Xml_AttributeValue => "di_attribute-value",
            GenericDecorationKind.Xml_AttributeOperator => "di_attribute-value",
            GenericDecorationKind.Xml_AttributeDelimiter => "di_attribute-value",
            GenericDecorationKind.Xml_TagNameNone => "di_tag-name",
            GenericDecorationKind.Xml_TagNameOpen => "di_tag-name",
            GenericDecorationKind.Xml_TagNameClose => "di_tag-name",
            GenericDecorationKind.Xml_TagNameSelf => "di_tag-name",
            GenericDecorationKind.Xml_Comment => "di_comment",
            GenericDecorationKind.Xml_CustomTagName => "di_te_custom-tag-name",
            GenericDecorationKind.Xml_EntityReference => "di_te_entity-reference",
            GenericDecorationKind.Xml_HtmlCode => "di_te_html-code",
            GenericDecorationKind.Xml_InjectedLanguageFragment => "di_injected-language-fragment",
            GenericDecorationKind.Xml_InjectedLanguageComponent => "di_injected-language-component",
            GenericDecorationKind.Xml_Error => "di_te_error",
            GenericDecorationKind.Xml_InjectedLanguageCodeBlock => "di_te_injected-language-code-block",
            GenericDecorationKind.Xml_InjectedLanguageCodeBlockTag => "di_te_injected-language-code-block-tag",
            GenericDecorationKind.Xml_InjectedLanguageKeyword => "di_keyword",
            GenericDecorationKind.Xml_InjectedLanguageTagHelperAttribute => "di_te_injected-language-tag-helper-attribute",
            GenericDecorationKind.Xml_InjectedLanguageTagHelperElement => "di_te_injected-language-tag-helper-element",
            GenericDecorationKind.Xml_InjectedLanguageMethod => "di_method",
            GenericDecorationKind.Xml_InjectedLanguageVariable => "di_variable",
            GenericDecorationKind.Xml_InjectedLanguageType => "di_type",
            GenericDecorationKind.Xml_InjectedLanguageStringLiteral => "di_string",
            ///
            GenericDecorationKind.Razor_AttributeName => "di_attribute-name",
            GenericDecorationKind.Razor_AttributeValue => "di_attribute-value",
            GenericDecorationKind.Razor_AttributeOperator => "di_attribute-value",
            GenericDecorationKind.Razor_AttributeDelimiter => "di_attribute-value",
            GenericDecorationKind.Razor_AttributeNameInjectedLanguageFragment => "di_injected-language-fragment",
            GenericDecorationKind.Razor_AttributeValueInjectedLanguageFragment => "di_injected-language-fragment",
            GenericDecorationKind.Razor_AttributeValueInterpolationStart => "di_attribute-value",
            GenericDecorationKind.Razor_AttributeValueInterpolationContinue => "di_attribute-value",
            GenericDecorationKind.Razor_TagNameNone => "di_tag-name",
            GenericDecorationKind.Razor_TagNameOpen => "di_tag-name",
            GenericDecorationKind.Razor_TagNameClose => "di_tag-name",
            GenericDecorationKind.Razor_TagNameSelf => "di_tag-name",
            GenericDecorationKind.Razor_Comment => "di_comment",
            GenericDecorationKind.Razor_CustomTagName => "di_te_custom-tag-name",
            GenericDecorationKind.Razor_EntityReference => "di_te_entity-reference",
            GenericDecorationKind.Razor_HtmlCode => "di_te_html-code",
            GenericDecorationKind.Razor_InjectedLanguageFragment => "di_injected-language-fragment",
            GenericDecorationKind.Razor_InjectedLanguageComponent => "di_injected-language-component",
            GenericDecorationKind.Razor_CSharpMarker => "di_type",
            GenericDecorationKind.Razor_Error => "di_te_error",
            GenericDecorationKind.Razor_InjectedLanguageCodeBlock => "di_te_injected-language-code-block",
            GenericDecorationKind.Razor_InjectedLanguageCodeBlockTag => "di_te_injected-language-code-block-tag",
            GenericDecorationKind.Razor_InjectedLanguageKeyword => "di_keyword",
            GenericDecorationKind.Razor_InjectedLanguageTagHelperAttribute => "di_te_injected-language-tag-helper-attribute",
            GenericDecorationKind.Razor_InjectedLanguageTagHelperElement => "di_te_injected-language-tag-helper-element",
            GenericDecorationKind.Razor_InjectedLanguageMethod => "di_method",
            GenericDecorationKind.Razor_InjectedLanguageVariable => "di_variable",
            GenericDecorationKind.Razor_InjectedLanguageType => "di_type",
            GenericDecorationKind.Razor_InjectedLanguageStringLiteral => "di_string",
            ///
            GenericDecorationKind.Terminal_Comment => "di_comment",
            GenericDecorationKind.Terminal_Keyword => "di_keyword",
            GenericDecorationKind.Terminal_StringLiteral => "di_string",
            GenericDecorationKind.Terminal_TargetFilePath => "di_type",
            GenericDecorationKind.Terminal_Error => "di_tree-view-exception",
            GenericDecorationKind.Terminal_Warning => "di_tree-view-warning",
            ///
            _ => string.Empty,
        };
    }
}
